
    create table appointment (
        appointment_type_id integer unique,
        date TIMESTAMP WITH TIME ZONE,
        end_time TIME WITH TIME ZONE,
        start_time TIME WITH TIME ZONE,
        client_id bigint,
        id bigint generated by default as identity,
        professional_id bigint,
        status varchar(255) check (status in ('PRESENT','ABSENT','OPEN','CANCEL')),
        primary key (id)
    );

    create table appointment_comment (
        appointment_id bigint,
        id bigint generated by default as identity,
        moment TIMESTAMP WITH TIME ZONE,
        comment varchar(1024),
        primary key (id)
    );

    create table appointment_type (
        id integer generated by default as identity,
        type varchar(255) unique,
        primary key (id)
    );

    create table area (
        id integer generated by default as identity,
        name varchar(40),
        primary key (id)
    );

    create table area_professional (
        area_id integer not null,
        professional_id bigint not null
    );

    create table client (
        date_of_birth date,
        person_id bigint not null,
        gender varchar(255) check (gender in ('MALE','FEMALE')),
        primary key (person_id)
    );

    create table person (
        id bigint generated by default as identity,
        phone varchar(20),
        email varchar(40) unique,
        name varchar(40) not null,
        comments varchar(1024),
        primary key (id)
    );

    create table professional (
        active boolean not null,
        person_id bigint not null,
        primary key (person_id)
    );

    create table work_schedule_item (
        day_of_week tinyint not null check (day_of_week between 0 and 6),
        end_time TIME WITH TIME ZONE,
        star_time TIME WITH TIME ZONE,
        id bigint generated by default as identity,
        professional_id bigint,
        primary key (id)
    );

    alter table if exists appointment 
       add constraint FK3gbqcfd3mnwwcit63lybpqcf8 
       foreign key (client_id) 
       references client;

    alter table if exists appointment 
       add constraint FK7y39ubfrch1jv1csekp9rmup6 
       foreign key (professional_id) 
       references professional;

    alter table if exists appointment 
       add constraint FKg6kjgj7k74ydmvh9nc3ttkggp 
       foreign key (appointment_type_id) 
       references appointment_type;

    alter table if exists appointment_comment 
       add constraint FKqcmtlqi6sbhsiuint9s43xrp5 
       foreign key (appointment_id) 
       references appointment;

    alter table if exists area_professional 
       add constraint FK7g9yue8sv3cqaa70idlkkdos6 
       foreign key (area_id) 
       references area;

    alter table if exists area_professional 
       add constraint FKm1if0exkiw55gxy1x3mjvlpid 
       foreign key (professional_id) 
       references professional;

    alter table if exists client 
       add constraint FKkxflpsue6s9kscgmuwt7ob1f3 
       foreign key (person_id) 
       references person;

    alter table if exists professional 
       add constraint FKoprncnoc2pi6bs2sdxj2ukyyn 
       foreign key (person_id) 
       references person;

    alter table if exists work_schedule_item 
       add constraint FKjj6v6dhvcf5yqpworikovugn8 
       foreign key (professional_id) 
       references professional;
